<?php

namespace AppBundle\Repository;

/**
 * ApiAccessScopeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiAccessScopeRepository extends \Doctrine\ORM\EntityRepository
{
}
