<?php

namespace AppBundle\Repository;

/**
 * ApiUserAccessCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiUserAccessCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
