<?php

namespace AppBundle\Repository;
use Doctrine\ORM\QueryBuilder;

/**
 * ApiUserAccessTokenScope
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiUserAccessTokenScopeRepository extends \Doctrine\ORM\EntityRepository{
	
	public function findAllTokenScope(){
		return $this->createQueryBuilder('a')
		->innerJoin("a.token","t")
		->addSelect('t')
		->innerJoin("a.scope","s")
		->addSelect('s')
		->innerJoin("t.application","app")
		->addSelect('app')
		->innerJoin("t.user","u")
		->addSelect('u');
	}

	public function whereToken(QueryBuilder $qb,$id){
		return $qb->andWhere('t.id = :token_id')
		->setParameter('token_id',$id);
	}

	public function whereScope(QueryBuilder $qb,$id){
		return $qb->andWhere('s.id = :scope_id')
		->setParameter('scope_id',$id);
	}

	public function whereApplication(QueryBuilder $qb,$id){
		return $qb->andWhere('app.id = :app_id')
		->setParameter('app_id',$id);
	}

	public function whereUser(QueryBuilder $qb,$id){
		return $qb->andWhere('u.id = :user_id')
		->setParameter('user_id',$id);
	}
}
