<?php

namespace AppBundle\Repository;

/**
 * ApiUserAccessTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiUserAccessTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
