<?php

namespace AppBundle\Repository;

/**
 * AppAccessScopeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppAccessScopeRepository extends \Doctrine\ORM\EntityRepository
{
}
