<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByEmailOrUsername($value){
		return $this->createQueryBuilder('u')
		->where('u.username = :value OR u.email = :value')
		->setParameter('value',$value)
		->getQuery()
		->getOneOrNullResult();
	}
}
